name: Bug Report
description: Something isn't working
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the issue
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Run these commands and paste the output
      value: |
        - macOS version: `sw_vers -productVersion`
        - Ruby version: `ruby -v`
        - claude-autoupdate version: `claude-autoupdate config`
        - claude-code installation: `brew list --cask claude-code`
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Paste output of: `tail -20 ~/Library/Logs/claude-autoupdate/claude-autoupdate.log`"
      render: shell
